version: "3"
services:
  web-app-flask:
    build: .
    container_name: 'sw_api_f2'
    command: sh -c 'python App.py'
    ports:
      - '5000:5000'
    volumes:
      - /home/nahuel/Escritorio/Parte 2/Parte2/api:/api
    depends_on:
      - "db-redis"

  db-redis:
    container_name: 'db_sw_api_f2'
    image: redis
    ports:
      - "6379:6379"
